FROM almalinux:9
ENV course="DevOps with AWS" \
    trainer="Shaik Nisar" \
    duration="120HRS"

#     [ ec2-user@ip-172-31-79-191 ~/Dockerfiles/ENV ]$ docker exec -it b9520e34b43f bash
# [root@b9520e34b43f /]# env
# HOSTNAME=b9520e34b43f
# PWD=/
# duration=120HRS
# HOME=/root
# LANG=C.utf8
# TERM=xterm
# LESSOPEN=||/usr/bin/lesspipe.sh %s
# SHLVL=1
# trainer=Shaik Nisar
# DEBUGINFOD_IMA_CERT_PATH=/etc/keys/ima:
# PATH=/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# course=DevOps with AWS
# _=/usr/bin/env
# [root@b9520e34b43f /]#
